
service: serverless-spotify

custom:
  bucket: finalexambucket
  table1: allsongs
  table2: newplaylist

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: us-west-2
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:us-west-2:*:*"
    - Effect: Allow
      Action:
        - s3:*
      Resource: "*"

functions:
  create:
    handler: handler.create
    events:
      - s3:
          bucket: ${self:custom.bucket}
          event: s3:ObjectCreated:*

  search:
    handler: handler.search
    events:
      - http:
          path: spotify/{songname}
          method: get
          cors: true

  list:
    handler: handler.list
    events:
      - http:
          path: spotify
          method: get
          cors: true
          
  playlist:
    handler: handler.playlist
    events:
      - http:
          path: spotify
          method: post
          cors: true
          
resources:
  Resources:
    ActivityTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: songname
            AttributeType: S
        KeySchema:
          - AttributeName: songname
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:custom.table1}

    NewPlayListTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: songname
            AttributeType: S
        KeySchema:
          - AttributeName: songname
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:custom.table2}